### ISSUE TITLE
cl/serv 공통 클래스 디자인

### ISSUE THREAD

**Issue by devwoodo** [devwoodo/chatters#30]
- [x] Token class
- [x] TokenManip class
- [x] PacketStream
- [x] PacketStreamManip : send/recv queue, message queue. #33`MessageQueue자료형..`
- [x] RequestHandling class
- [x] RequestHandlingManip class : request queue
- [x] #35 `PacketStream issue`

선행작업 : #31, #32 
후행작업 : #31`각 Info class별로 member로 Token 넣기`

**Comment by devwoodo** [comment]
원본 백업
--------
- [ ] PacketStream
- [ ] sending 구현
- [ ] receiving 구현 #34`TCP packet boundary prob.`
- [x] message queue 클래스 #33`MessageQueue자료형..`
- [x] #35 `PacketStream issue`
- [ ] 각 Info class 별로 Token class 구현.

선행작업 : #31, #32 
후행작업 : #31`각 Info class별로 member로 Token 넣기`
